- hosts: hetzner
  gather_facts: false

  tasks:
  - name: update system
    become: yes
    dnf:
      name: '*'
      state: latest

  - name: install libvirt and kvm 
    become: yes
    dnf:
      name: qemu-kvm,qemu-img,libvirt,virt-install,libvirt-client,libguestfs-tools 
      state: present

  - name: start libvirtd service
    become: yes
    systemd:
      name: libvirtd
      state: started
      enabled: yes
