- hosts: hetzner
  gather_facts: false

  tasks:
  - name: update system
    become: yes
    yum:
      name: '*'
      state: latest

  - name: install libvirt and kvm 
    become: yes
    yum:
      name: qemu-kvm,libvirt,libguestfs-tools,virt-install
      state: latest

  - name: start libvirtd service
    become: yes
    systemd:
      name: libvirtd
      state: started
      enabled: yes
